// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"airbnb-messaging-be/internal/app/sms/api/event"
	"airbnb-messaging-be/internal/app/sms/repo/repoimpl"
	"airbnb-messaging-be/internal/app/sms/usecase/usecaseimpl"
	"airbnb-messaging-be/internal/pkg/env"
	"airbnb-messaging-be/internal/pkg/env/tool"
	"airbnb-messaging-be/internal/pkg/gorm"
	"airbnb-messaging-be/internal/pkg/http/server"
	"airbnb-messaging-be/internal/pkg/http/server/router"
	"airbnb-messaging-be/internal/pkg/kafka"
	"airbnb-messaging-be/internal/pkg/kafka/consumer"
	"airbnb-messaging-be/internal/pkg/kafka/producer"
	router2 "airbnb-messaging-be/internal/pkg/kafka/router"
	"airbnb-messaging-be/internal/pkg/messagebird"
	"github.com/google/wire"
)

import (
	_ "airbnb-messaging-be/docs"
)

// Injectors from wire.go:

func NewApp() (*App, error) {
	config := env.ProvideEnv()
	configConfig := tool.ExtractServerConfig(config)
	engine := router.NewRouter()
	options := server.Options{
		Config: configConfig,
		Router: engine,
	}
	serverServer := server.NewServer(options)
	config2 := tool.ExtractKafkaConsumerConfig(config)
	config3 := tool.ExtractKafkaConfig(config)
	config4 := tool.ExtractKafkaRouterConfig(config)
	routerOptions := router2.Options{
		Config: config4,
	}
	routerRouter := router2.NewRouter(routerOptions)
	kafkaOptions := kafka.Options{
		Config: config3,
		Router: routerRouter,
	}
	client := kafka.NewSaramaClient(kafkaOptions)
	consumerOptions := consumer.Options{
		Config: config2,
		Client: client,
		Router: routerRouter,
	}
	listener := consumer.NewEventListener(consumerOptions)
	producerOptions := producer.Options{
		Client: client,
	}
	producerProducer := producer.NewEventProducer(producerOptions)
	config5 := tool.ExtractDBConfig(config)
	gormOptions := gorm.Options{
		Config: config5,
	}
	gormEngine := gorm.NewORM(gormOptions)
	repoimplOptions := repoimpl.Options{
		Gorm: gormEngine,
	}
	repo := repoimpl.NewSmsRepo(repoimplOptions)
	config6 := tool.ExtractMessengerConfig(config)
	messagebirdOptions := messagebird.Options{
		Config: config6,
	}
	messenger := messagebird.InitMessenger(messagebirdOptions)
	usecaseimplOptions := usecaseimpl.Options{
		SmsRepo:   repo,
		Messenger: messenger,
	}
	usecase := usecaseimpl.NewSmsUsecase(usecaseimplOptions)
	eventOptions := event.Options{
		Sms:    usecase,
		Router: routerRouter,
	}
	handler := event.NewSmsHandler(eventOptions)
	appOptions := Options{
		HttpServer:    serverServer,
		EventListener: listener,
		EventProducer: producerProducer,
		SmsHandler:    handler,
	}
	app := &App{
		Options: appOptions,
	}
	return app, nil
}

// wire.go:

var AppSet = wire.NewSet(wire.Struct(new(Options), "*"), wire.Struct(new(App), "*"))
